[[mgr.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Close"

[[mgr.prepend_keymap]]
on   = "`"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = "R"
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list',
		"yank" ]
