[font]
size = 10.0

[font.normal]
family = "Fira Code"

[colors.primary]
background = "#111111"

[[hints.enabled]]
regex = '([\w\.\/]{3,}):(\d+):'
command = { program = "vimat.sh" }
mouse = { enabled = true, mods = "None" }
binding = { key = "Space", mods = "Control" }
